### ISSUE TITLE
Doesn't work on Quilt

### ISSUE THREAD

**Issue by pyj-pd** [LitnhJacuzzi/CursorCentered-Fix#3]
Hello, I am trying to use this mod on Quilt 1.20.1. However, I noticed the mod doesn't center the mouse at all after opening, closing, and reopening inventory, chat, or chest GUIs.

I am sure the mod is loaded since it shows up on Modmenu.

**Comment by LitnhJacuzzi** [comment]
Hi, which version of mod do you use? I've tried 1.20.1-fabric and it works fine for me.

**Comment by pyj-pd** [comment]
I am using Quilt Loader 0.21.0. I think there is something different between Fabric and Quilt rendering the GUI.

**Comment by LitnhJacuzzi** [comment]
Weird, Quilt 0.21.0 also works for me. Could you provide more details(such as game logs) with it?
Note that this mod is not relevant with GUI rendering, the only factor to cause problems is mixin exception on Fabric. See #2 for how it works.

**Comment by pyj-pd** [comment]
https://mclo.gs/RUXZuIr
Here is the log with no mods but this mod installed only.

Isn't this mod about preserving cursor position even after closing and reopening GUIs, like it does on Bedrock Edition?

**Comment by LitnhJacuzzi** [comment]
The log doesn't show any exception about the mod, it should work properly, I need more descriptions to identify your problem:
1.When the cursor was hidden by the game, was there a GUI showing?
2.Did the game window never lose its focus during your test?

MC JE itself has mouse centering method invoked before opening a GUI and after closing a GUI, however the mouse state is wrong to set the position of cursor before opening a GUI, only centering operations after closing a GUI are valid. So if the game window gains its focus without any GUI opening, the cursor can only be centered before a GUI opening which cause the original bug. This mod fix the bug by manually set the correct mouse state for the centering method invoked before opening a GUI.

**Comment by pyj-pd** [comment]
I'm sorry but I still don't understand the purpose of the mod. Can I ask you for the example video if you don't mind?

**Comment by LitnhJacuzzi** [comment]
This mod actually fixes this bug: https://bugs.mojang.com/browse/MC-150164

**Comment by pyj-pd** [comment]
I think I misunderstood. I will close the issue. Thank you for the help! Have a nice day.

**Comment by LitnhJacuzzi** [comment]
You are welcome :)
