### ISSUE TITLE
crash on startup with Modrinth App [fabric versions 1.19-1.20.4]

### ISSUE THREAD

**Issue by TheRedstoneShark** [LitnhJacuzzi/CursorCentered-Fix#5]
When using the Modrinth App, adding CursorCentered Fix to an fabric instance and attempting to start the instance, Minecraft crashes immediately (adding fabric api doesn't change anything).

This applies to versions 1.19-1.20.4. This is not an issue when using the vanilla Minecraft launcher, or with any other mod I've used.

### Full Logs:
✔️ 1.21 (no crash): https://mclo.gs/lpy0S4W
✔️ 1.20.6 (no crash): https://mclo.gs/IjuCswX
✔️ 1.20.5 (no crash): https://mclo.gs/EWkLKBU
❌ 1.20.4 (crash): https://mclo.gs/2l1rJmM
❌ 1.20.3 (crash): https://mclo.gs/ywUstFa
❌ 1.20.2 (crash): https://mclo.gs/CloXsJn
❌ 1.20.1 (crash): https://mclo.gs/nqRQwTt
❌ 1.20 (crash): https://mclo.gs/IaJH8RM
❌ 1.19.4 (crash): https://mclo.gs/ieZMqfg
❌ 1.19.3 (crash): https://mclo.gs/Dm41cHX
❌ 1.19.2 (crash): https://mclo.gs/6jrB56d
❌ 1.19.1 (crash): https://mclo.gs/w16ISib (attempt 2: https://mclo.gs/ScmVyZu)
❌ 1.19 (crash): https://mclo.gs/lPh0u97

**Comment by LitnhJacuzzi** [comment]
Use Java 21 instead of Java 17 (versions you've launched successfully are using Java 21, see line 7 in your logs).
