### ISSUE TITLE
Newest version needs java21

### ISSUE THREAD

**Issue by Mrpressed** [LitnhJacuzzi/CursorCentered-Fix#6]
needs java21 even in 1.20.1

**Comment by LitnhJacuzzi** [comment]
This has been mentioned in #5 and currently not planned to backport since Java 21 has no problem with the newest version of fabric loader for 1.17~1.21. If you really need to use it with Java 17 just download the older mod version, there's no functional change in the newer version.

**Comment by Mrpressed** [comment]
Yea but, when you have exports and modpacks you can't force Java versions.

**Comment by LitnhJacuzzi** [comment]
It's probably a launcher specific issue. However, to avoid more potential issues caused by this I'll manage to make the newest version be compatible with Java 17.
